### ISSUE TITLE
LONG/LATI: Problem when mixed Event/LOC data

### ISSUE THREAD

**Issue by ungeahnt** [vesta-webtrees-2-custom-modules/vesta_common#100]
When I add LONG/LATI coordiantes directly to an birth place (E8 and N45) which also has LOC coordinates (N48.9833 and E9.45873), then I see the number of the map icons increased from 4 to 7 and all icons are linked only to the birth place LONG/LATI coordinates (see red marking in the screenshot below and [here: Birth Place](https://proavitus.de/tree/proavitus/individual/P7/Karoline-Martha-Buhler))

-> There should be only 4 map icons (linked to the birth place).

![grafik](https://user-images.githubusercontent.com/28572767/211633062-71b1e7c4-ac91-4dc2-9016-461fec0b7450.png)

Link to the LOC data: https://proavitus.de/tree/proavitus/sharedPlace/X81/Oppenweiler

Additionally the url from the first bing icon includes strange html code: 

`https://www.bing.com/maps/?v=2&cp=45~8&lvl=10&dir=0&sty=o&sp=point.45_8_ — <span class="error" title="Unbekannter GEDCOM Code">_DUMMY:EVEN</span>
`

**Comment by ric2016** [comment]
Bing broken url:
Fixed in Vesta release 2.1.16.0.0.
