### ISSUE TITLE
set ⚶ central

### ISSUE THREAD

**Issue by Gunnar-GO** [vesta-webtrees-2-custom-modules/vesta_common#3]
it would be easier and more consitent if the decission about the ⚶ symbol could set at one place.

Since it is used for every plugin it should / could be set in central, that would keep the plugins together. At Common and Webtrees Location Data Provider it can't be set, while the other resides at Vesta. I not exactly see the need, that it needs to be removed under admin/modules, but it sets the plugins at the lower bottom between ka and ja language. 

I set it primarily for the frontend so i get a clean and similar interface.

so maybe it's a nice enhancement. 

//since it refers to all i posted it under commons

**Comment by ric2016** [comment]
> I not exactly see the need, that it needs to be removed under admin/modules

There isn't one, really. This is mainly a leftover from webtrees 1.x, where you couldn't distinguish between module title and tab title. I'll probably remove the option.

> I set it primarily for the frontend so i get a clean and similar interface.

That's the intended use case. Still, for me it is more straightforward and less confusing to have the tab/chart/menu titles configurable for each module separately. Anyway you'll only have to do this once.

**Comment by ric2016** [comment]
> I'll probably remove the option.

Removed in latest release.
