### ISSUE TITLE
Benutzerdefinierte deutsche Übersetzung wird nicht geladen

### ISSUE THREAD

**Issue by mpwt** [vesta-webtrees-2-custom-modules/vesta_common#40]
Hallo,

kann es sein, dass eine benutzerdefinierte Übersetzung per Modul nicht (mehr) richt geladen wird. Ich habe einen Punkt aus Ihrem Add-on anders übersetzt - mit Deutsch (de) funktioniert es nicht, mit Englisch (en-US) funktioniert es.

Deutsch (hier sollte stehen: Ereignisse verbundener Personen)
<img width="579" alt="Übersetzung_de" src="https://user-images.githubusercontent.com/16311627/132947120-dd0b2ce1-3aae-4d4b-9806-fe26f90ea71f.png">

Englisch
<img width="485" alt="Übersetzung_en-US" src="https://user-images.githubusercontent.com/16311627/132947154-c829d16b-53f3-473d-8488-aa0d58da4906.png">

Haben Sie eine Idee, woran das liegen könnte? Ich nutze diese Übersetzung auf zwei Seiten. Auf beiden habe ich unterschiedlich viele Ihrer Add-ons installiert (Seite 1 mit 6 Stück, Seite 2 mit nur drei Stück). Mit dem aktuellen Update wird die benutzerdefinierte Übersetzung für Deutsch auf keiner Seite mehr richtig genutzt.

**Comment by ric2016** [comment]
> Haben Sie eine Idee, woran das liegen könnte?

Nein - wie funktioniert "eine benutzerdefinierte Übersetzung per Modul" denn grundsätzlich, insbesondere im Zusammenhang mit Custom Modules? Vielleicht ist die Reihenfolge, in der die Übersetzungen aus den Modulen geladen werden, da nicht passend definiert, und es hat bisher bzw. für einzelne Sprachen eher zufällig funktioniert? Wobei man erwarten würde, daß es sich wenigstens einheitlich verhalten würde für alle Sprachen.

**Comment by mpwt** [comment]
Vielen Dank für die super schnelle Antwort. Im Ordner modules_v4 gibt es die Vorlage example.disable, welche für webtrees angepasst werden kann. Diese habe ich mit webtrees v2 in Änderung zur früheren Lösung über eine de.po im Unterordner data/language genutzt. Sie werden recht haben, dass dies scheinbar nur zufällig auch bei custom modules funktioniert. Anliegend meine verwendete Datei zur Info.
[module.php.zip](https://github.com/vesta-webtrees-2-custom-modules/vesta_common/files/7147847/module.php.zip)

Wie werden denn bei Ihren Modulen ggf. benutzerdefinierte Übersetzungen geladen? Vielleicht sollten ja solche Übersetzungen weiterhin im data/language-Ordner verbleiben.

**Comment by ric2016** [comment]
Die beschriebene Lösung funktioniert zuverlässig für Ersetzungen bzgl. Strings aus dem webtrees-Kern. 

Für Custom Modules ist die Reihenfolge der Module relevant, in der diese von webtrees abgearbeitet werden. Aktuell scheint dies in alphabetischer Reihenfolge der Ordnernamen zu geschehen (es ist aber unklar, ob man sich darauf verlassen kann). Wenn man somit das Modul mit den Ersetzungen hinter 'vesta_personal_facts' setzt (z.B. Ordnername 'zzz'), funktioniert es bei mir auch für Deutsch. 

Warum es allerdings für Englisch auch in der anderen Reihenfolge funktioniert, ist mir nicht klar.

Alternativ können Ersetzungen auch im Ordner 'resources/lang' des jeweiligen Vesta-Moduls als csv-Dateien abgelegt werden, das ist vielleicht zuverlässiger. Siehe [de.csv](https://github.com/vesta-webtrees-2-custom-modules/vesta_common/files/7147931/de.csv).

**Comment by mpwt** [comment]
Vielen Dank. Die Lösung mit dem Ordnername funktioniert bei mir nicht (oder ich mache etwas falsch).

Die mit der de.csv funktioniert. Ich habe jetzt beide Seiten darauf umgestellt.

Soll ich die Frage zur Übersetzung von Custom Modules mal in webtrees stellen?

**Comment by ric2016** [comment]
> Die Lösung mit dem Ordnername funktioniert bei mir nicht (oder ich mache etwas falsch).

Möglicherweise ist die Sortierung nicht einheitlich z.B. auf verschiedenen Dateisystemen.

> Soll ich die Frage zur Übersetzung von Custom Modules mal in webtrees stellen?

Ja, gerne - Wobei alle Themen bzgl. Custom Modules anscheinend sehr niedrige Priorität haben leider.
