### ISSUE TITLE
v2.1.0.0.0 - Changing language in Control panel is not possible

### ISSUE THREAD

**Issue by TheDutchJewel** [vesta-webtrees-2-custom-modules/vesta_common#61]
In webtrees it is possible to change language from menu. That works fine in webtrees 2.1 without modules, both in the Control panel and in My page.

But as soon as I add the vesta module v2.1.0.0.0, it does not work anymore in the Control panel: then I have to go to My page to change the language there.

**Comment by ric2016** [comment]
Will be fixed in next release.

**Comment by ric2016** [comment]
Fixed in latest release.
