### ISSUE TITLE
Bug in Place Hierarchy (WT 2.1)

### ISSUE THREAD

**Issue by heiler** [vesta-webtrees-2-custom-modules/vesta_common#66]
When clicking on a city I get the following:
Non-static method Cissee\WebtreesExt\Functions\FunctionsFactAssociates::getOutputForRelationshipFallback() cannot be called statically …/modules_v4/vesta_common/patchedWebtrees/functions/FunctionsFactAssociates.php:53
#0 …/modules_v4/vesta_common/patchedWebtrees/functions/FunctionsFactAssociates.php(126): Cissee\WebtreesExt\Functions\FunctionsFactAssociates::getOutputForRelationship()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#1 …/modules_v4/vesta_common/resources/views/fact.phtml(188): Cissee\WebtreesExt\Functions\FunctionsFactAssociates::getHtmlAndPushScript()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#2 …/app/View.php(183): include('...')
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#3 …/app/View.php(278): Fisharebest\Webtrees\View->render()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#4 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#5 …/modules_v4/vesta_common/resources/views/lists/place-history.phtml(145): view()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#6 …/app/View.php(183): include('...')
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#7 …/app/View.php(278): Fisharebest\Webtrees\View->render()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#8 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#9 …/modules_v4/vesta_places_and_pedigree_map/resources/views/modules/generic-place-hierarchy/events.phtml(91): view()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#10 …/app/View.php(183): include('...')
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#11 …/app/View.php(278): Fisharebest\Webtrees\View->render()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#12 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#13 …/modules_v4/vesta_common/patchedWebtrees/Http/Controllers/GenericPlaceHierarchyController.php(116): view()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#14 …/app/Http/Middleware/RequestHandler.php(54): Cissee\WebtreesExt\Http\Controllers\GenericPlaceHierarchyController->handle()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#16 …/app/Http/Middleware/CheckCsrf.php(76): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#19 …/app/Webtrees.php(265): Middleland\Dispatcher->dispatch()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#20 …/app/Http/Middleware/Router.php(153): Fisharebest\Webtrees\Webtrees::dispatch()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#22 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
vesta-webtrees-2-custom-modules/vesta_common#66 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#26 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#28 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#29 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#30 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#32 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#34 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#36 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#38 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
#39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#40 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#42 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#44 …/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle()
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#46 …/app/Http/Middleware/BadBotBlocker.php(233): Middleland\Dispatcher->handle()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#48 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#50 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#52 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#53 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#55 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#57 …/app/Http/Middleware/BaseUrl.php(79): Middleland\Dispatcher->handle()
#58 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#59 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#60 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#61 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#62 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#63 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#64 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#65 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#66 …/app/Webtrees.php(265): Middleland\Dispatcher->dispatch()
#67 …/app/Webtrees.php(252): Fisharebest\Webtrees\Webtrees::dispatch()
#68 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#69 {main}

**Comment by ric2016** [comment]
Fixed in latest release (2.1.1.0.0).
