### ISSUE TITLE
Nicht übersetzter Begriff

### ISSUE THREAD

**Issue by mpwt** [vesta-webtrees-2-custom-modules/vesta_common#70]
Ich glaube, es gibt eine nicht übersetzten Wortgruppe „No relationship found“:

![048CFE16-60E4-4488-BAB7-45B722B7E0AC](https://user-images.githubusercontent.com/16311627/168152177-c9194f34-9459-46e3-aca6-d96be7af4a35.jpeg)

In keiner Übersetzungsdatei konnte ich sie bisher finden.

**Comment by ric2016** [comment]
War bisher in webtrees selbst übersetzbar. 
Ist jetzt in weblate verfügbar (in Vesta Common)
