### ISSUE TITLE
Extended Relationship - Error message 

### ISSUE THREAD

**Issue by SnarfW** [vesta-webtrees-2-custom-modules/vesta_common#76]
With Webtrees 2.1.2 & Vesta 2.1.2.1.0 I get the following error on the fact and events tab of one person (others show without errors). Not sure what triggers the error, I do not see anything particular in the Gedcom of this person.

![afbeelding](https://user-images.githubusercontent.com/25879600/169594251-2cc23421-8f77-447e-b835-52cb12238a98.png)

**Comment by ric2016** [comment]
Fixed in latest release 2.1.2.1.3.
