### ISSUE TITLE
Disabling Vesta when webtrees is upgrading

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_common#88]
When webtrees is upgrading the Vesta modules are now disabled automatically. In general a good idea.

It would be nice if the standard tabs for "Facts and events" and "Families" could be enabled in this case automatically. Otherwise, it is not possible to use webtrees anymore.

Is it possible to enable Vesta modules again? I didn't find a possibility to do this at my own risk. The folders do not contain ".disable" and in the control panel, it looks like that the Vesta modules are enabled.

**Comment by ric2016** [comment]
They are still enabled, but do not provide any functionality. You can modify this in the module.php files by removing the placeholder parts, e.g. here: <https://github.com/vesta-webtrees-2-custom-modules/vesta_extended_relationships/blob/c6ec2d64019875743709c74cb1d63fe588a9f18a/module.php#L52>

I'm reluctant to add an option for this, it will just lead to errors in case of breaking changes. We need a better module management in webtrees, but apparently that's not going to happen :-(

**Comment by hartenthaler** [comment]
> We need a better module management in webtrees ...

You are right!

**Comment by ungeahnt** [comment]
> I'm reluctant to add an option for this, it will just lead to errors in case of breaking changes. We need a better module management in webtrees, but apparently that's not going to happen :-(

This must be solved in general in webtrees and not in each add-on module separat! Even if the update behavior of the Vesta modules at least allow a stable state, the problem is that most wt users have modules from several vendors installed and each module behaves differently. As long as there is no unique solution, wt updates are really annoying.

It's a pity that modules in wt are treated so negligently.

**Comment by ric2016** [comment]
> It's a pity that modules in wt are treated so negligently.

Yes, but a compatibiliy check would be required in any case, unless webtrees would use a stricter version numbering system where patch releases would only be used for non-breaking changes.

**Comment by ric2016** [comment]
Note: 'Placeholder' message will be extended, see https://github.com/vesta-webtrees-2-custom-modules/vesta_common/issues/89.
