### ISSUE TITLE
ERROR: Only webtrees versions before 2.1.7 are supported

### ISSUE THREAD

**Issue by JesseWebDotCom** [vesta-webtrees-2-custom-modules/vesta_common#89]
Updated to webtrees 2.1.7 and now all vesta modules are disabled with the following error message:
`This version of the module is incompatible with your current webtrees version. Only webtrees versions before 2.1.7 are supported. All functionality of the module is therefore disabled.`

**Comment by ric2016** [comment]
Expanded message in release 2.1.7.0.0
