### ISSUE TITLE
vesta-modules: how to get older versions?

### ISSUE THREAD

**Issue by ungeahnt** [vesta-webtrees-2-custom-modules/vesta_common#95]
I've updated wt to V2.1.8 and also the vesta modules via https://cissee.de/vesta.latest.zip.

But now I have problems with other custom modules and have switched back to wt V2.1.7 for the time being. Now the current Vesta modules no longer work with V2.1.7. 

Can I download the previous Vesta version (as a complete package) somewhere?

**Comment by ric2016** [comment]
The final 2.1.7 version is still available here:
<https://cissee.de/releases/vesta.2.1.7.1.1.zip>

I may have to add links to older versions somewhere.

**Comment by ungeahnt** [comment]
Thanks!
